version: "3"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    tty: true
    working_dir: /data
    command: >
      streamlit run streamlit_app.py --server.port=8080 --server.address=0.0.0.0
    ports:
      - 8000:8080
    volumes:
      - .:/data
    depends_on:
      - api-app
    networks:
      - olanet
  api-app:
    build:
      context: .
      dockerfile: Dockerfile.api
    tty: true
    working_dir: /data
    command: >
      gunicorn  --bind 0.0.0.0:5858 api:app --worker-class uvicorn.workers.UvicornWorker --timeout 0
    ports:
      - 5858:5858
    volumes:
      - .:/data
    networks:
      - olanet

networks:
  olanet:
    driver: bridge